### ISSUE TITLE
Failed build with GCC 5.1.0 (exception specification) (Bugzilla #679)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#898]
**Imported from Bugzilla**
Reporter: *Rupert Swarbrick (Broadcom)*
Status: *RESOLVED*
Severity: *normal*
Assigned to: *Cristian Mattarei*
Component: *Build system (configure, make, make install)*
Milestone: *1.5*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[0001-Fix-build-with-GCC-5.1.0.patch](http://cvc4.cs.stanford.edu/bugzilla_attachments/323_0001-Fix-build-with-GCC-5.1.0.patch)_ (Fix build with GCC 5.1.0, ID 323)
- _[noexcept.patch](http://cvc4.cs.stanford.edu/bugzilla_attachments/383_noexcept.patch)_ (patch to make cvc4 pass with gcc6, ID 383)
- _[bug_679.patch](http://cvc4.cs.stanford.edu/bugzilla_attachments/384_bug_679.patch)_ (alternative compile fix for gcc-6, ID 384)

On 2015-10-07 05:30:35 -0700, Rupert Swarbrick (Broadcom) wrote:
> I'm building with the following parameters:
> 
> time env PKG\_CONFIG\_PATH\=.../cln/lib/pkgconfig \
>             GCCVER\=5.1.0 \
>             SWIG\=.../swig \
>             ANTLR\_HOME\=.../antlr/3.4 \
>             CPPFLAGS\="\-I.../cln/include \-I...gmp/include" \
>             LDFLAGS\=\-L.../termcap/lib \
>      ../cvc4/configure \-\-prefix\=.../cvc4 \
>                        \-\-enable\-optimized \
>                        \-\-enable\-proof \
>                        \-\-enable\-static\-binary \
>                        \-\-with\-boost\=.../1.55.0 \
>                        \-\-best \
>                        \-\-enable\-gpl \
>                        \-\-with\-glpk\=no \
>                        \-\-with\-abc\=no \
>                        \-\-with\-readline\=no \
>                        \-\-disable\-thread\-support \
>                        \-\-disable\-shared \
>                        \-\-enable\-static
> 
> (the "..." are elided paths which are internal to the company: they point to sensible places. GCCVER controls a wrapper script around GCC and causes us to get GCC 5.1.0)
> 
>    env GCCVER\=5.1.0 make
> 
> I see the following error:
> 
>   In file included from ../../cvc4/src/theory/quantifiers\_engine.cpp:41:0:
>   ../../cvc4/src/theory/quantifiers/quant\_equality\_engine.h: At global scope:
>   ../../cvc4/src/theory/quantifiers/quant\_equality\_engine.h:67:3: error: looser throw specifier for 'virtual CVC4::theory::quantifiers::QuantEqualityEngine::\~QuantEqualityEngine() throw (CVC4::AssertionException)'
>      \~QuantEqualityEngine(){}
>      ^
>   In file included from ../../cvc4/src/theory/quantifiers\_engine.cpp:15:0:
>   ../../cvc4/src/theory/quantifiers\_engine.h:53:11: error:   overriding 'virtual CVC4::theory::QuantifiersModule::\~QuantifiersModule() noexcept'
>      virtual \~QuantifiersModule(){}
>              ^
> 
> This is with SHA 6343fbb0c9b238aeb1addca6449f95a01071c1ac (head as of 7/10/15)
> 
> Adding a "noexcept" to the definition on line 67 of quant\_equality\_engine.h allows the build to continue.

On 2015-10-07 06:15:02 -0700, Rupert Swarbrick (Broadcom) wrote:
> I didn't realise when I raised this bug originally, but there's also a problem with some code to extract a float from an istringstream in src/main/driver\_unified.cpp
> 
> I'm attaching a patch that seems to get everything working.

On 2015-10-07 06:15:42 -0700, Rupert Swarbrick (Broadcom) wrote:
> Created attachment 323
> Fix build with GCC 5.1.0

On 2016-07-25 07:55:25 -0700, Johannes Kanig wrote:
> Created attachment 383
> patch to make cvc4 pass with gcc6
> 
> I encountered the same problem when trying to compile cvc4 with gcc 6.1.1. Some more changes in the same vein as the patch by Rupert were needed. The attached patch achieves this.

On 2016-07-25 08:02:32 -0700, Florian Schanda wrote:
> I'd like to raise the priority of this since we're moving our build infrastructure to gcc 6...

On 2016-07-25 09:13:56 -0700, Florian Schanda wrote:
> Created attachment 384
> alternative compile fix for gcc\-6
> 
> Attached is a smaller compiled fix. This one marks the affected base classes destructors as noexcept(false) which I think is a bit more in the spirit of what noexcept was meant to do (as far as I understand it anyway, I am not a C\+\+ expert).

On 2016-07-25 09:33:23 -0700, Florian Schanda wrote:
> (In reply to comment \# 5)
> > Attached is a smaller compiled fix. This one marks the affected base classes> destructors as noexcept(false) which I think is a bit more in the spirit of
> > what noexcept was meant to do (as far as I understand it anyway, I am not a C\+\+
> > expert).
> 
> I should not that adding "\-std\=gnu\+\+11" to my CXXFLAGS allows me to build
> the patched version with the standard debian g\+\+; without it it will fail.

On 2016-07-31 21:31:34 -0700, Johannes Kanig wrote:
> Hello,
> 
> In fact the easiest fix to this problem is to include "\-std\=gnu\+\+98" in the CXXFLAGS. This requires no patch at all and should work with all GCC versions including 4.x.
> 
> The underlying problem was likely that gcc 5 and 6 change the default version of compilation to some later version.
> 
> Maybe it should be considered to add tis option to the CVC4 compilation flags?
