### ISSUE TITLE
build does not work with GNU GCC 8.2.1 on x86_64

### ISSUE THREAD

**Issue by pointhi** [CVC4/CVC4#2845]
```
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
```

There seems to be a comparison of a pointer (64 bit) and an integer (32 bit):

```
./cvc4-git/src/CVC4/src/parser/antlr_line_buffered_input.cpp: In function 'void CVC4::parser::bufferedInputSeek(pANTLR3_INT_STREAM, ANTLR3_MARKER)':
./cvc4-git/src/CVC4/src/parser/antlr_line_buffered_input.cpp:291:41: error: cast from 'void*' to 'ANTLR3_MARKER' {aka 'int'} loses precision [-fpermissive]
   while ((ANTLR3_MARKER)(input->nextChar) != seekPoint) {
                                         ^
make[2]: *** [src/parser/CMakeFiles/cvc4parser.dir/build.make:153: src/parser/CMakeFiles/cvc4parser.dir/antlr_line_buffered_input.cpp.o] Error 1
```

**Comment by 4tXJ7f** [comment]
Interesting, I am actually using GCC 8.2.1 as well and haven't encountered that error yet. How did you install ANTLR? Which version of ANTLR are you using? `ANTLR3_MARKER` should actually be an `int64_t` on a 64-bit system. If you compile ANTLR from source, you may have to use the flag `--enable-64bit` when configuring it. If you haven't done so, you can also use the `contrib/get-antlr-3.4` script in the CVC4 folder. This script downloads and compiles the correct version of ANTLR.

**Comment by aniemetz** [comment]
Closed due to inactivity.

**Comment by panda2134** [comment]
> Interesting, I am actually using GCC 8.2.1 as well and haven't encountered that error yet. How did you install ANTLR? Which version of ANTLR are you using? `ANTLR3_MARKER` should actually be an `int64_t` on a 64-bit system. If you compile ANTLR from source, you may have to use the flag `--enable-64bit` when configuring it. If you haven't done so, you can also use the `contrib/get-antlr-3.4` script in the CVC4 folder. This script downloads and compiles the correct version of ANTLR.

This works for me! Additionally, if running the script `get-antlr-3.4` doesn't work correctly, try setting the environment variable `MACHINE_TYPE`; this can be useful if you're installing CVC with `pysmt`.

```sh
export MACHINE_TYPE='x86_64'
```
